<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantRepository extends EntityRepository
{
}
